#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import re
import argparse
import subprocess
import tempfile
from typing import Dict, Optional

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from tqdm import tqdm



def smiles_to_3d_xyz(smiles: str) -> Optional[str]:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 2024
    try:
        cid = AllChem.EmbedMolecule(mol, params)
        if cid < 0:
            return None
        AllChem.UFFOptimizeMolecule(mol, maxIters=200)
    except Exception:
        return None

    conf = mol.GetConformer()
    lines = []
    n_atoms = mol.GetNumAtoms()
    lines.append(str(n_atoms))
    lines.append("Generated by RDKit")
    for i in range(n_atoms):
        atom = mol.GetAtomWithIdx(i)
        pos = conf.GetAtomPosition(i)
        lines.append(
            f"{atom.GetSymbol():2s}  {pos.x: .8f}  {pos.y: .8f}  {pos.z: .8f}"
        )
    return "\n".join(lines) + "\n"


def run_xtb_on_xyz(
    xyz_str: str,
    xtb_cmd: str = "xtb",
    workdir: Optional[str] = None
) -> Optional[str]:

    tmp_dir = tempfile.mkdtemp(dir=workdir)
    xyz_path = os.path.join(tmp_dir, "mol.xyz")
    with open(xyz_path, "w") as f:
        f.write(xyz_str)

    cmd = [xtb_cmd, "mol.xyz", "--opt", "--gfn", "2", "--dipole"]
    try:
        proc = subprocess.run(
            cmd,
            cwd=tmp_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=600,  
        )
    except Exception:
        return None

    if proc.returncode != 0:
        return None

    return proc.stdout



def parse_xtb_output(out: str) -> Dict[str, float]:

    res = {
        "xtb_Etot_Ha": np.nan,
        "xtb_HOMO_eV": np.nan,
        "xtb_LUMO_eV": np.nan,
        "xtb_gap_eV": np.nan,
        "xtb_dipole_D": np.nan,
    }

    # --- total energy (Hartree) ---
    m = re.search(r"total\s+energy\s+(-?\d+\.\d+)\s+Eh", out, re.IGNORECASE)
    if m:
        res["xtb_Etot_Ha"] = float(m.group(1))

    # --- EHOMO / ELUMO / gap ---
    m_homo = re.search(r"EHOMO\s+(-?\d+\.\d+)\s+eV", out, re.IGNORECASE)
    m_lumo = re.search(r"ELUMO\s+(-?\d+\.\d+)\s+eV", out, re.IGNORECASE)
    m_gap = re.search(r"HOMO-?LUMO\s+GAP\s+(-?\d+\.\d+)\s+eV", out, re.IGNORECASE)
    m_dipole = re.search(r"total\s*\(Debye\)\s*:\s*(-?\d+\.\d+)", out)

    if m_homo:
        res["xtb_HOMO_eV"] = float(m_homo.group(1))
    if m_lumo:
        res["xtb_LUMO_eV"] = float(m_lumo.group(1))
    if m_dipole:
        res["xtb_dipole_D"] = float(m.group(1))

    if m_gap:
        res["xtb_gap_eV"] = float(m_gap.group(1))
    elif np.isfinite(res["xtb_HOMO_eV"]) and np.isfinite(res["xtb_LUMO_eV"]):
        res["xtb_gap_eV"] = res["xtb_LUMO_eV"] - res["xtb_HOMO_eV"]

    m_d1 = re.search(
        r"molecular\s+dipole[^\n]*:\s+(-?\d+\.\d+)\s+Debye",
        out,
        re.IGNORECASE,
    )
    if m_d1:
        res["xtb_dipole_D"] = float(m_d1.group(1))
    else:
        m_block = re.search(
            r"molecular\s+dipole[^\n]*\n\s*([-\d\.Ee\s]+)\n",
            out,
            re.IGNORECASE,
        )
        if m_block:
            parts = m_block.group(1).split()
            if len(parts) >= 4:
                try:
                    res["xtb_dipole_D"] = float(parts[3])
                except Exception:
                    pass

    return res



def main(args):
    df = pd.read_csv(args.csv)
    print(f"Loaded {args.csv}, shape={df.shape}")

    smiles_col = None
    for c in ["smiles_for_qm", "smiles_std", "smiles"]:
        if c in df.columns:
            smiles_col = c
            break
    if smiles_col is None:
        raise ValueError("找不到 SMILES 列（需要 smiles_for_qm 或 smiles_std 或 smiles）")

    print(f"Using SMILES column: {smiles_col}")

    qm_cols = ["xtb_HOMO_eV", "xtb_LUMO_eV", "xtb_gap_eV", "xtb_dipole_D", "xtb_Etot_Ha"]
    for qc in qm_cols:
        if qc not in df.columns:
            df[qc] = np.nan

    mask_has_smiles = df[smiles_col].notna() & (df[smiles_col].astype(str).str.len() > 0)

    if args.only_missing:
        mask_need = mask_has_smiles & df["xtb_Etot_Ha"].isna()
    else:
        mask_need = mask_has_smiles

    idx_list = df.index[mask_need].tolist()
    total = len(idx_list)
    print(f"Total rows: {len(df)}, need xTB calc: {total}")

    has_mol_id = "mol_id" in df.columns

    for i, idx in enumerate(tqdm(idx_list, desc="Running xTB")):
        smi = df.at[idx, smiles_col]
        try:
            xyz_str = smiles_to_3d_xyz(smi)
        except Exception:
            xyz_str = None
        if xyz_str is None:
            print(f"[{i+1}/{total}] SMILES -> 3D 失败，跳过: {smi}", flush=True)
            continue

        out = run_xtb_on_xyz(xyz_str, xtb_cmd=args.xtb_cmd, workdir=args.tmpdir)
        if out is None:
            print(f"[{i+1}/{total}] xTB 运行失败，跳过: {smi}", flush=True)
            continue

        props = parse_xtb_output(out)
        for k, v in props.items():
            df.at[idx, k] = v

        mol_tag = df.at[idx, "mol_id"] if has_mol_id else idx
        print(
            f"[{i+1}/{total}] mol={mol_tag} | "
            f"Etot={props['xtb_Etot_Ha']:.6f} Ha | "
            f"HOMO={props['xtb_HOMO_eV']:.3f} eV | "
            f"LUMO={props['xtb_LUMO_eV']:.3f} eV | "
            f"gap={props['xtb_gap_eV']:.3f} eV | "
            f"dipole={props['xtb_dipole_D']:.3f} D",
            flush=True,
        )

    out_path = args.out
    df.to_csv(out_path, index=False)
    print(f"Saved with extended quantum features to: {out_path}")
    print("Columns now include:", qm_cols)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compute multiple xTB quantum properties for molecules in CSV.")
    parser.add_argument("--csv", type=str, required=True, help="输入 CSV 路径")
    parser.add_argument("--out", type=str, required=True, help="输出 CSV 路径")
    parser.add_argument("--xtb_cmd", type=str, default="xtb", help="xtb 可执行文件名或绝对路径")
    parser.add_argument("--tmpdir", type=str, default=None, help="可选：指定临时目录根路径")
    parser.add_argument(
        "--only_missing",
        action="store_true",
        help="只对 xtb_Etot_Ha 为空的分子计算（避免覆盖已有结果）",
    )
    args = parser.parse_args()
    main(args)
